### ISSUE TITLE
Cannot Paste Contract Address

### ISSUE THREAD

**Issue by Callum-A** [oraichain/vscode-cosmwasm#22]
Hi there,

Been starting to check this out after someone on InterWasm tipped me about it. I can't paste a contract address into the contract address field.

System info:
MacBook pre M1

Steps to reproduce:
Open up the CW-IDE tab
Copy an address from somewhere, for me I used one from my browser
Upon pressing Command-V in the input box nothing is pasted

**Comment by phuctu1901** [comment]
I also had the same problem. And maybe this is not a problem unique to Cosmwasm IDE. You can copy/paste by Edit->Copy/Edit->Paste.

**Comment by im6h** [comment]
Yes, this is a problem for the vscode extension on Mac os

**Comment by ducphamle2** [comment]
This is a known issue when using VSCode webview on VSCode desktop version of macOS. If you are using macOS, you can try using Gitpod instead to use the IDE.
