### ISSUE TITLE
Transaction with ID ... was submitted but was not yet found on the chain. You might want to check later.

### ISSUE THREAD

**Issue by nhatcl-smartosc** [oraichain/vscode-cosmwasm#26]
- I added a new chain (Malaga) with the JSON file below:
`{
    "rpc": "https://rpc.malaga-420.cosmwasm.com",
    "rest": "https://api.malaga-420.cosmwasm.com",
    "chainId": "malaga-420",
    "chainName": "Malaga",
    "stakeCurrency": {
        "coinDenom": "Málaga",
        "coinMinimalDenom": "umlg",
        "coinDecimals": 6,
        "coinImageUrl": ""
    },
    "bip44": {
        "coinType": 118
    },
    "bech32Config": {
        "bech32PrefixAccAddr": "wasm",
        "bech32PrefixAccPub": "wasmpub",
        "bech32PrefixConsAddr": "wasmvalcons",
        "bech32PrefixConsPub": "wasmvalconspub",
        "bech32PrefixValAddr": "wasmvaloper",
        "bech32PrefixValPub": "wasmvaloperpub"
    },
    "currencies": [
        {
            "coinDenom": "Málaga",
            "coinMinimalDenom": "umlg",
            "coinDecimals": 6,
            "coinImageUrl": ""
        }
    ],
    "feeCurrencies": [
        {
            "coinDenom": "Málaga",
            "coinMinimalDenom": "umlg",
            "coinDecimals": 6,
            "coinImageUrl": ""   
        }
    ],
    "gasPriceStep": {
        "low": 0,
        "average": 0.0025,
        "high": 0.004
    },
    "features": [
        "stargate",
        "ibc-transfer",
        "cosmwasm"
    ],
    "cosmwasmVersion": "0.13.2"
}`
- The Malaga testnet was added successfully
- Then I deployed a sample smart contract, and an error message pushed out:
 `Error message
Error: Transaction with ID 1C0890BD3FC1951FE3926A0B1C69E3AD5E9C30CD5CA72B89EDD3D1B4EC6A7358 was submitted but was not yet found on the chain. You might want to check later.`
- I don't know where the problem is. I also deployed the contract to Oraichain and it's okay.

**Comment by ducphamle2** [comment]
@nhatcl-smartosc  I hate when this error happens. It usually means that there's an error when broadcasting the transaction, probably something that the Cosmjs library cannot display. The lib should have showed the error better.

Nonetheless, I saw that you are using cosmwasmVersion: "0.13.2", which is probably not correct. Can you identify the cosmwasm std version of the Malaga network?

I believe it's 1.0, but im not 100% sure

**Comment by nhatcl-smartosc** [comment]
@ducphamle2 It means the smart contract has been compiled successfully but can not broadcast, right? 
And you're right; the Malaga network uses Cosmwasm v1.0.0 refer to the document: https://github.com/CosmWasm/testnets. I think it might be the issue. Let me check.

**Comment by nhatcl-smartosc** [comment]
@ducphamle2 `Error: Query failed with (18): failed to execute message; message index: 0: Error calling the VM: Error during static Wasm validation: Wasm contract missing a required marker export: interface_version_*: create wasm contract failed: invalid request` 
it works! But another error was pushed out.

**Comment by ducphamle2** [comment]
https://github.com/cosmos/cosmjs/tree/main/packages/cosmwasm-stargate

dont know if it's still related to the cosmwasm version or not. Here, the CosmWasm stargate currently supports up to x/wasmd 0.23, while the Malaga network is using x/wasmd 0.27

**Comment by ducphamle2** [comment]
looks like the cosmwasm-vm is different

**Comment by ducphamle2** [comment]
let me try pumping the cosmwasm stargate version to the latest version. Wait me a moment

**Comment by nhatcl-smartosc** [comment]
This error happened because of the old version of the smart contract, I agreed. But when I deploy another smart contract with a similar cosmwasm version, a new error pushed out: 
`Error: Broadcasting transaction failed with code 13 (codespace: sdk). Log: insufficient fees; got: 3257umlg required: 65124umlg: insufficient fee`
my address is `wasm19epkyc6rneyp05c0tkd9rlcakxguf8n6wkmnjd`, and I requested faucet token before deployment.

**Comment by nhatcl-smartosc** [comment]
It looks like it's a mistake from `gasPriceStep` in configuration

**Comment by nhatcl-smartosc** [comment]
Thanks, @ducphamle2. I deployed successfully. This is the configuration for Malaga network:
`{
    "rpc": "https://rpc.malaga-420.cosmwasm.com",
    "rest": "https://api.malaga-420.cosmwasm.com",
    "chainId": "malaga-420",
    "chainName": "Malaga",
    "stakeCurrency": {
        "coinDenom": "Málaga",
        "coinMinimalDenom": "umlg",
        "coinDecimals": 6,
        "coinImageUrl": ""
    },
    "bip44": {
        "coinType": 118
    },
    "bech32Config": {
        "bech32PrefixAccAddr": "wasm",
        "bech32PrefixAccPub": "wasmpub",
        "bech32PrefixConsAddr": "wasmvalcons",
        "bech32PrefixConsPub": "wasmvalconspub",
        "bech32PrefixValAddr": "wasmvaloper",
        "bech32PrefixValPub": "wasmvaloperpub"
    },
    "currencies": [
        {
            "coinDenom": "Málaga",
            "coinMinimalDenom": "umlg",
            "coinDecimals": 6,
            "coinImageUrl": ""
        }
    ],
    "feeCurrencies": [
        {
            "coinDenom": "Málaga",
            "coinMinimalDenom": "umlg",
            "coinDecimals": 6,
            "coinImageUrl": ""   
        }
    ],
    "gasPriceStep": {
        "low": 0,
        "average": 0.25,
        "high": 0.004
    },
    "features": [
        "stargate",
        "ibc-transfer",
        "cosmwasm"
    ],
    "cosmwasmVersion": "1.0.0"
}`

**Comment by ducphamle2** [comment]
Awesome! Let me add the configuration into the code so it is natively integrated
