### ISSUE TITLE
Unable to add network

### ISSUE THREAD

**Issue by nhatcaoo** [oraichain/vscode-cosmwasm#27]
Hi team. 
- I added a new chain (Dev server network) with the JSON file below:
`{
    "rpc": "http://10.1.0.44:26657",
    "rest": "http://10.1.0.44:1317",
    "chainId": "baseblockchain",
    "chainName": "baseblockchain",
    "stakeCurrency": {
        "coinDenom": "stake",
        "coinMinimalDenom": "stake",
        "coinDecimals": 6,
        "coinImageUrl": ""
    },
    "bip44": {
        "coinType": 118
    },
    "bech32Config": {
        "bech32PrefixAccAddr": "sosc",
        "bech32PrefixAccPub": "soscpub",
        "bech32PrefixConsAddr": "soscvalcons",
        "bech32PrefixConsPub": "soscvalconspub",
        "bech32PrefixValAddr": "soscvaloper",
        "bech32PrefixValPub": "soscvaloperpub"
    },
    "currencies": [
        {
            "coinDenom": "token",
            "coinMinimalDenom": "token",
            "coinDecimals": 6,
            "coinImageUrl": ""
        }
    ],
    "feeCurrencies": [
        {
            "coinDenom": "stake",
            "coinMinimalDenom": "stake",
            "coinDecimals": 6,
            "coinImageUrl": ""   
        }
    ],
    "gasPriceStep": {
        "low": 0,
        "average": 0.0025,
        "high": 0.004
    },
    "features": [
        "stargate",
        "ibc-transfer",
        "cosmwasm"
    ],
    "cosmwasmVersion": "1.0.0"
}`
- The network was added successfully
- Then I deployed a sample smart contract, and an error message pushed out:
`TypeError: Failed to fetch`
Where could this error come from?

**Comment by ducphamle2** [comment]
@nhatcaoo can you connect to `http://10.1.0.44:26657` locally? The ip address looks sus

**Comment by nhatcaoo** [comment]
@ducphamle2 Yes, the address point to our internal Cosmwasm endpoint. Everything about the server was okay because I deployed a smart contract on it by using go cli, but not the same for Cosmwasm IDE.

**Comment by ducphamle2** [comment]
@nhatcaoo I found the bug. It's related to the CORS policy. You should try updating CORS of RPC: `http://localhost:26657` in config.toml to ["*"]

**Comment by nhatcaoo** [comment]
@ducphamle2 Did you mean we need to update the config on Wasmd Repo on the server? We can't find it.

**Comment by ducphamle2** [comment]
> @ducphamle2 Did you mean we need to update the config on Wasmd Repo on the server? We can't find it.

There should be a .wasm or .wasmd directory that stores all the config & data of your local network. Pls seek .wasm (or .wasmd)/config/config.toml and you will be able to find the cors option for RPC

**Comment by nhatcaoo** [comment]
Thanks, I've just found the config. But it has already been set.
`
# TCP or UNIX socket address for the RPC server to listen on
laddr = "tcp://0.0.0.0:26657"

# A list of origins a cross-domain request can be executed from
# Default value '[]' disables cors support
# Use '["*"]' to allow any origin
cors_allowed_origins = ["*", ]

# A list of methods the client is allowed to use with cross-domain requests
cors_allowed_methods = ["HEAD", "GET", "POST", ]

# A list of non simple headers the client is allowed to use with cross-domain requests
cors_allowed_headers = ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time", ]
`

**Comment by ducphamle2** [comment]
can you try removing the `,` character & restart the network to apply the change?

**Comment by nhatcaoo** [comment]
Thanks, I've just found the config. But it has already been set.
[config.log](https://github.com/oraichain/cw-ide-vscode/files/9443410/config.log)

**Comment by nhatcaoo** [comment]
> can you try removing the `,` character & restart the network to apply the change?

Let me try

**Comment by nhatcaoo** [comment]
@ducphamle2 I did change the config by removing the `,` character and redeploying it. Everything is going well. The error `TypeError: Failed to fetch` has been gone for a while. But after 4-5 times I make the contract deploy request, it returns and stays till now.

**Comment by ducphamle2** [comment]
> @ducphamle2 I did change the config by removing the `,` character and redeploying it. Everything is going well. The error `TypeError: Failed to fetch` has been gone for a while. But after 4-5 times I make the contract deploy request, it returns and stays till now.

I see. Let me investigate this

**Comment by ducphamle2** [comment]
@nhatcaoo, it seems that it's entirely related to the RPC. Did you receive the `TypeError: Failed to fetch` everytime, or is it a hit or miss case?

**Comment by nhatcaoo** [comment]
@ducphamle2 It's happends every time.

**Comment by ducphamle2** [comment]
> @ducphamle2 It's happends every time.

that's weird. Can you open the developer tools on VSCode and capture the error you got when you try to deploy?

![image](https://user-images.githubusercontent.com/44611780/188328751-e8025cef-5e4a-441e-ac81-9a372b5c72a9.png)

**Comment by nhatcaoo** [comment]
![image](https://user-images.githubusercontent.com/39726840/188414296-fb964f82-71d1-4310-aad1-139ce7fd79b9.png)
@ducphamle2 any clue?

**Comment by ducphamle2** [comment]
@nhatcaoo most browsers by default blocks HTTP contents, but they may allow local contents. Reference: 
![image](https://user-images.githubusercontent.com/44611780/188777236-fa8a4b78-a9f4-481e-88a2-d6f4f74e20a8.png)

do you really need to use a specific IP address instead of using localhost?

**Comment by ducphamle2** [comment]
As far as I know, it's not possible to fix this problem, unless we specifically update the browser to allow all mixed content, which is really dangerous & can potentially poses security risks

**Comment by nhatcaoo** [comment]
@ducphamle2 So, the problem comes from HTTP blocking of the extension.
 I have to use the Ip address because the Cosmwasm core runs on a LAN server. Can we config the extension/ browser to allow HTTP contents?

**Comment by ducphamle2** [comment]
> @ducphamle2 So, the problem comes from HTTP blocking of the extension. I have to use the Ip address because the Cosmwasm core runs on a LAN server. Can we config the extension/ browser to allow HTTP contents?

I don't think we can. Users can allow insecure content on their browser & use the IDE's desktop local version, but not the Gitpod web version. Have you tried adding cert files for your node?

![image](https://user-images.githubusercontent.com/44611780/189515110-0a84eda5-85ea-4d7f-adab-7a109a60040e.png)
