### ISSUE TITLE
Passing Mnemonic through local `.env`

### ISSUE THREAD

**Issue by arnabghose997** [oraichain/vscode-cosmwasm#40]
I was trying to build and deploy the WASM binary to Osmosis Testnet. I am reffering to the dev `.env` file (https://github.com/oraichain/cw-ide-vscode/blob/master/.env.development) but it doesn't show the exact field name to pass the Wallet mnemonic.

What would be the exact field name that we have provide in the `.env` file?

**Comment by ducphamle2** [comment]
You should only put mnemonic in it, no need to put any key or something
The .env should be created in the root contract workspace

Take a look at this tutorial: https://github.com/oraichain/cw-ide-docs/tree/master/installation-usage#tutorials

if it is still unclear, I can update the document

**Comment by ducphamle2** [comment]
the .env content in the root workspace can be: foo bar hello world

**Comment by arnabghose997** [comment]
@ducphamle2 

When you refer to only putting the mnemonic in local `.env` without any key, do you something like the following:

```
WDS_SOCKET_HOST=localhost
WDS_SOCKET_PORT=3000
PORT=3001
BROWSER=false
"<mnemonic string>"
```

Or have I misunderstood the approach?

**Comment by ducphamle2** [comment]
> @ducphamle2
> 
> When you refer to only putting the mnemonic in local `.env` without any key, do you something like the following:
> 
> ```
> WDS_SOCKET_HOST=localhost
> WDS_SOCKET_PORT=3000
> PORT=3001
> BROWSER=false
> "<mnemonic string>"
> ```
> 
> Or have I misunderstood the approach?

The .env is not related to the one written in the .env.development in cw-ide-vscode

it is a completely new .env in the root workspace of your contract directory

like this:

```
<mnemonic-string>
```

**Comment by arnabghose997** [comment]
Thanks @ducphamle2, it worked. I would suggest you to add this instruction here: https://github.com/oraichain/cw-ide-docs/blob/master/installation-usage/local-tutorial.md , for others to refer to

**Comment by ducphamle2** [comment]
Thanks for your suggestion. I'll add it in the local-tutorial.md
